version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      PORT: ${PORT}    # PORT viene escrito en .env.production desde el workflow
    volumes:
      - sqlite_data:/app/db
      - storage_data:/app/storage
    ports:
      - "${PORT}:${PORT}"

volumes:
  sqlite_data:
  storage_data:
