services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PORT: ${PORT}
      RAILS_SERVE_STATIC_FILES: true
    volumes:
      - sqlite_data:/app/db
      - storage_data:/app/storage
    ports:
      - "${PORT}:${PORT}"

volumes:
  sqlite_data:
  storage_data:
